from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EliminarProductoWindow(object):
    # ! -------- Código autogenerado ----------
    def setupUi(self, EliminarProductoWindow):
        EliminarProductoWindow.setObjectName("EliminarProductoWindow")
        EliminarProductoWindow.resize(632, 269)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./icons/bxs-trash.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        EliminarProductoWindow.setWindowIcon(icon)
        self.button_cancelarEli = QtWidgets.QPushButton(EliminarProductoWindow)
        self.button_cancelarEli.setGeometry(QtCore.QRect(330, 220, 112, 38))
        self.button_cancelarEli.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./icons/bxs-message-square-x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_cancelarEli.setIcon(icon)
        self.button_cancelarEli.setIconSize(QtCore.QSize(30, 30))
        self.button_cancelarEli.setObjectName("button_cancelarEli")
        self.lb_codEli = QtWidgets.QLabel(EliminarProductoWindow)
        self.lb_codEli.setGeometry(QtCore.QRect(210, 50, 48, 16))
        self.lb_codEli.setObjectName("lb_codEli")
        self.button_eliminar = QtWidgets.QPushButton(EliminarProductoWindow)
        self.button_eliminar.setGeometry(QtCore.QRect(180, 220, 111, 38))
        self.button_eliminar.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./icons/bxs-trash.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_eliminar.setIcon(icon1)
        self.button_eliminar.setIconSize(QtCore.QSize(30, 30))
        self.button_eliminar.setObjectName("button_eliminar")
        self.lb_titleEli = QtWidgets.QLabel(EliminarProductoWindow)
        self.lb_titleEli.setGeometry(QtCore.QRect(190, 10, 215, 23))
        self.lb_titleEli.setObjectName("lb_titleEli")
        self.le_codEli = QtWidgets.QLineEdit(EliminarProductoWindow)
        self.le_codEli.setGeometry(QtCore.QRect(270, 50, 133, 22))
        self.le_codEli.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.le_codEli.setObjectName("le_codEli")
        self.tb_eliminarProd = QtWidgets.QTableWidget(EliminarProductoWindow)
        self.tb_eliminarProd.setGeometry(QtCore.QRect(10, 90, 614, 115))
        self.tb_eliminarProd.setObjectName("tb_eliminarProd")
        self.tb_eliminarProd.setColumnCount(6)
        self.tb_eliminarProd.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_eliminarProd.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_eliminarProd.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_eliminarProd.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_eliminarProd.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_eliminarProd.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_eliminarProd.setHorizontalHeaderItem(5, item)

        self.retranslateUi(EliminarProductoWindow)
        QtCore.QMetaObject.connectSlotsByName(EliminarProductoWindow)

    def retranslateUi(self, EliminarProductoWindow):
        _translate = QtCore.QCoreApplication.translate
        EliminarProductoWindow.setWindowTitle(_translate("EliminarProductoWindow", "Eliminar Producto"))
        self.button_cancelarEli.setText(_translate("EliminarProductoWindow", "CANCELAR"))
        self.lb_codEli.setText(_translate("EliminarProductoWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">CODIGO</span></p></body></html>"))
        self.button_eliminar.setText(_translate("EliminarProductoWindow", "ELIMINAR"))
        self.lb_titleEli.setText(_translate("EliminarProductoWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">ELIMINAR PRODUCTO</span></p></body></html>"))
        item = self.tb_eliminarProd.horizontalHeaderItem(0)
        item.setText(_translate("EliminarProductoWindow", "CODIGO"))
        item = self.tb_eliminarProd.horizontalHeaderItem(1)
        item.setText(_translate("EliminarProductoWindow", "NOMBRE"))
        item = self.tb_eliminarProd.horizontalHeaderItem(2)
        item.setText(_translate("EliminarProductoWindow", "STOCK"))
        item = self.tb_eliminarProd.horizontalHeaderItem(3)
        item.setText(_translate("EliminarProductoWindow", "PRECIO_UNITARIO"))
        item = self.tb_eliminarProd.horizontalHeaderItem(4)
        item.setText(_translate("EliminarProductoWindow", "DESCUENTO"))
        item = self.tb_eliminarProd.horizontalHeaderItem(5)
        item.setText(_translate("EliminarProductoWindow", "PROVEEDOR"))
    # ! ---------------------------------------


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EliminarProductoWindow = QtWidgets.QWidget()
    ui = Ui_EliminarProductoWindow()
    ui.setupUi(EliminarProductoWindow)
    EliminarProductoWindow.show()
    sys.exit(app.exec_())