from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from screens.fix_deprecate import suppress_qt_warnings
from screens.realizar_factura import Ui_RealizarFacturaWindow
from screens.busqueda_producto import Ui_BusquedaProductoWindow
from screens.agregar_producto import Ui_AddProductWindow
from screens.eliminar_producto import Ui_EliminarProductoWindow
from screens.modificar_producto import Ui_ModificarProductoWindow
from screens.ver_inventario import Ui_VerInventarioWindow
from screens.generar_reporte import Ui_GenerarReporteWindow
from screens.factura_x_cliente import Ui_FacturaClienteWindow
from screens.agregar_prov import Ui_AgregarProvWindow
from screens.modificar_prov import Ui_ModificarProvWindow
from screens.eliminar_prov import Ui_EliminarProvWindow
from screens.buscar_prov import Ui_BuscarProvWindow


class Ui_MainWindow(object):
    # ! -------- Código autogenerado ----------
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(730, 661)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./icons/bxs-store-alt.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lb_logo = QtWidgets.QLabel(self.centralwidget)
        self.lb_logo.setGeometry(QtCore.QRect(20, 10, 231, 71))
        self.lb_logo.setText("")
        self.lb_logo.setPixmap(QtGui.QPixmap("./icons/logo_small.png"))
        self.lb_logo.setScaledContents(True)
        self.lb_logo.setObjectName("lb_logo")
        self.tb_detalle = QtWidgets.QTableWidget(self.centralwidget)
        self.tb_detalle.setGeometry(QtCore.QRect(10, 100, 711, 361))
        self.tb_detalle.setObjectName("tb_detalle")
        self.tb_detalle.setColumnCount(7)
        self.tb_detalle.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_detalle.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_detalle.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_detalle.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_detalle.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_detalle.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_detalle.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_detalle.setHorizontalHeaderItem(6, item)
        self.lb_sub = QtWidgets.QLabel(self.centralwidget)
        self.lb_sub.setGeometry(QtCore.QRect(530, 470, 91, 16))
        self.lb_sub.setObjectName("lb_sub")
        self.lb_iva = QtWidgets.QLabel(self.centralwidget)
        self.lb_iva.setGeometry(QtCore.QRect(580, 530, 41, 16))
        self.lb_iva.setObjectName("lb_iva")
        self.lb_valT = QtWidgets.QLabel(self.centralwidget)
        self.lb_valT.setGeometry(QtCore.QRect(510, 560, 121, 16))
        self.lb_valT.setObjectName("lb_valT")
        self.lb_des = QtWidgets.QLabel(self.centralwidget)
        self.lb_des.setGeometry(QtCore.QRect(520, 500, 101, 16))
        self.lb_des.setObjectName("lb_des")
        self.lb_subCom = QtWidgets.QLabel(self.centralwidget)
        self.lb_subCom.setGeometry(QtCore.QRect(630, 470, 71, 16))
        self.lb_subCom.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lb_subCom.setObjectName("lb_subCom")
        self.le_des = QtWidgets.QLineEdit(self.centralwidget)
        self.le_des.setGeometry(QtCore.QRect(630, 500, 71, 20))
        self.le_des.setObjectName("le_des")
        self.le_iva = QtWidgets.QLineEdit(self.centralwidget)
        self.le_iva.setGeometry(QtCore.QRect(630, 530, 71, 20))
        self.le_iva.setObjectName("le_iva")
        self.lb_valTCom = QtWidgets.QLabel(self.centralwidget)
        self.lb_valTCom.setGeometry(QtCore.QRect(630, 560, 71, 16))
        self.lb_valTCom.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lb_valTCom.setObjectName("lb_valTCom")
        self.button_Factura = QtWidgets.QPushButton(self.centralwidget)
        self.button_Factura.setGeometry(QtCore.QRect(520, 590, 161, 41))
        self.button_Factura.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_Factura.setStyleSheet("font: 75 9pt \"MS Shell Dlg 2\";")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./icons/bx-cart-add.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_Factura.setIcon(icon1)
        self.button_Factura.setIconSize(QtCore.QSize(35, 35))
        self.button_Factura.setFlat(False)
        self.button_Factura.setObjectName("button_Factura")
        self.lb_slogan = QtWidgets.QLabel(self.centralwidget)
        self.lb_slogan.setGeometry(QtCore.QRect(390, 10, 191, 31))
        self.lb_slogan.setStyleSheet("color: rgb(0, 170, 127);")
        self.lb_slogan.setObjectName("lb_slogan")
        self.ln_head = QtWidgets.QFrame(self.centralwidget)
        self.ln_head.setGeometry(QtCore.QRect(270, 30, 431, 16))
        self.ln_head.setFrameShape(QtWidgets.QFrame.HLine)
        self.ln_head.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ln_head.setObjectName("ln_head")
        self.lb_dir = QtWidgets.QLabel(self.centralwidget)
        self.lb_dir.setGeometry(QtCore.QRect(270, 40, 61, 16))
        self.lb_dir.setObjectName("lb_dir")
        self.ld_dirCom = QtWidgets.QLabel(self.centralwidget)
        self.ld_dirCom.setGeometry(QtCore.QRect(330, 40, 221, 16))
        self.ld_dirCom.setObjectName("ld_dirCom")
        self.lb_tel = QtWidgets.QLabel(self.centralwidget)
        self.lb_tel.setGeometry(QtCore.QRect(560, 40, 61, 16))
        self.lb_tel.setObjectName("lb_tel")
        self.lb_telCom = QtWidgets.QLabel(self.centralwidget)
        self.lb_telCom.setGeometry(QtCore.QRect(620, 40, 61, 16))
        self.lb_telCom.setObjectName("lb_telCom")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 730, 21))
        self.menubar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.menubar.setObjectName("menubar")
        self.menuProductos = QtWidgets.QMenu(self.menubar)
        self.menuProductos.setObjectName("menuProductos")
        self.menuBusqueda = QtWidgets.QMenu(self.menubar)
        self.menuBusqueda.setObjectName("menuBusqueda")
        self.menuReportes = QtWidgets.QMenu(self.menubar)
        self.menuReportes.setObjectName("menuReportes")
        self.menuProveedores = QtWidgets.QMenu(self.menubar)
        self.menuProveedores.setObjectName("menuProveedores")
        MainWindow.setMenuBar(self.menubar)
        self.actionBusqueda = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./icons/bx-search-alt.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBusqueda.setIcon(icon2)
        self.actionBusqueda.setObjectName("actionBusqueda")
        self.actionModificar = QtWidgets.QAction(MainWindow)
        self.actionModificar.setIcon(icon)
        self.actionModificar.setObjectName("actionModificar")
        self.actionAgregar = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./icons/bxs-message-square-add.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAgregar.setIcon(icon3)
        self.actionAgregar.setObjectName("actionAgregar")
        self.actionEliminar = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("./icons/bxs-message-square-x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEliminar.setIcon(icon4)
        self.actionEliminar.setObjectName("actionEliminar")
        self.actionInventario_2 = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(".icons/bxs-data.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInventario_2.setIcon(icon5)
        self.actionInventario_2.setObjectName("actionInventario_2")
        self.actionFactura_x_Cliente = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("./icons/bxs-file-doc.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFactura_x_Cliente.setIcon(icon6)
        self.actionFactura_x_Cliente.setObjectName("actionFactura_x_Cliente")
        self.actionCliente = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("./icons/bx-body.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCliente.setIcon(icon7)
        self.actionCliente.setObjectName("actionCliente")
        self.actionVer_Inventario = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("./icons/bxs-data.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVer_Inventario.setIcon(icon8)
        self.actionVer_Inventario.setObjectName("actionVer_Inventario")
        self.actionGenerar = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("./icons/bxs-file-plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGenerar.setIcon(icon9)
        self.actionGenerar.setObjectName("actionGenerar")
        self.actionBuscarProv = QtWidgets.QAction(MainWindow)
        self.actionBuscarProv.setIcon(icon2)
        self.actionBuscarProv.setObjectName("actionBuscarProv")
        self.actionModificarProv = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("./icons/bxs-notepad.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionModificarProv.setIcon(icon10)
        self.actionModificarProv.setObjectName("actionModificarProv")
        self.actionAgregarProv = QtWidgets.QAction(MainWindow)
        self.actionAgregarProv.setIcon(icon3)
        self.actionAgregarProv.setObjectName("actionAgregarProv")
        self.actionEliminarProv = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("./icons/bxs-trash.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEliminarProv.setIcon(icon11)
        self.actionEliminarProv.setObjectName("actionEliminarProv")
        self.menuProductos.addAction(self.actionBusqueda)
        self.menuProductos.addAction(self.actionModificar)
        self.menuProductos.addAction(self.actionAgregar)
        self.menuProductos.addAction(self.actionEliminar)
        self.menuBusqueda.addAction(self.actionFactura_x_Cliente)
        self.menuReportes.addAction(self.actionVer_Inventario)
        self.menuReportes.addAction(self.actionGenerar)
        self.menuProveedores.addAction(self.actionBuscarProv)
        self.menuProveedores.addAction(self.actionModificarProv)
        self.menuProveedores.addAction(self.actionAgregarProv)
        self.menuProveedores.addAction(self.actionEliminarProv)
        self.menubar.addAction(self.menuProductos.menuAction())
        self.menubar.addAction(self.menuBusqueda.menuAction())
        self.menubar.addAction(self.menuReportes.menuAction())
        self.menubar.addAction(self.menuProveedores.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Veci\'s Market - Sistema Administrador"))
        item = self.tb_detalle.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "CODIGO"))
        item = self.tb_detalle.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NOMBRE"))
        item = self.tb_detalle.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "CANTIDAD"))
        item = self.tb_detalle.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "EN STOCK"))
        item = self.tb_detalle.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "VALOR UNITARIO"))
        item = self.tb_detalle.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "DESCUENTO"))
        item = self.tb_detalle.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "VALOR FINAL"))
        self.lb_sub.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">SUBTOTAL</span></p></body></html>"))
        self.lb_iva.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">I.V.A</span></p></body></html>"))
        self.lb_valT.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">VALOR TOTAL</span></p></body></html>"))
        self.lb_des.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#0055ff;\">DESCUENTO</span></p></body></html>"))
        self.lb_subCom.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.lb_valTCom.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.button_Factura.setText(_translate("MainWindow", "REALIZAR FACTURA"))
        self.lb_slogan.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Todo a tu alcance !</span></p></body></html>"))
        self.lb_dir.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Dirección: </span></p></body></html>"))
        self.ld_dirCom.setText(_translate("MainWindow", "Av. Francisco de Galarza y Naciones Unidas."))
        self.lb_tel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Teléfono:</span></p></body></html>"))
        self.lb_telCom.setText(_translate("MainWindow", "0961731848"))
        self.menuProductos.setTitle(_translate("MainWindow", "Productos"))
        self.menuBusqueda.setTitle(_translate("MainWindow", "Busqueda"))
        self.menuReportes.setTitle(_translate("MainWindow", "Reportes"))
        self.menuProveedores.setTitle(_translate("MainWindow", "Proveedores"))
        self.actionBusqueda.setText(_translate("MainWindow", "Buscar"))
        self.actionModificar.setText(_translate("MainWindow", "Modificar"))
        self.actionAgregar.setText(_translate("MainWindow", "Agregar"))
        self.actionEliminar.setText(_translate("MainWindow", "Eliminar"))
        self.actionInventario_2.setText(_translate("MainWindow", "Inventario"))
        self.actionFactura_x_Cliente.setText(_translate("MainWindow", "Factura_x_Cliente"))
        self.actionCliente.setText(_translate("MainWindow", "Cliente"))
        self.actionVer_Inventario.setText(_translate("MainWindow", "Ver_Inventario"))
        self.actionGenerar.setText(_translate("MainWindow", "Generar..."))
        self.actionBuscarProv.setText(_translate("MainWindow", "Buscar"))
        self.actionModificarProv.setText(_translate("MainWindow", "Modificar"))
        self.actionAgregarProv.setText(_translate("MainWindow", "Agregar"))
        self.actionEliminarProv.setText(_translate("MainWindow", "Eliminar"))
    # ! ---------------------------------------


    # ? ------ Funcionalidades Propias --------
    def open_PrincipalWindow(self):
        suppress_qt_warnings()
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()

        # ? Abrir 'realizar_factura' 
        ui.button_Factura.clicked.connect(self.abrir_factura)

        # ? Añadir eventos a las opciones del 'menu bar'
        ui.actionAgregar.triggered.connect(lambda: self.abrir_agregar_producto())    
        ui.actionBusqueda.triggered.connect(lambda: self.abrir_busqueda_produto())
        ui.actionEliminar.triggered.connect(lambda: self.abrir_eliminar_producto())
        ui.actionModificar.triggered.connect(lambda: self.abrir_modificar_producto())
        ui.actionVer_Inventario.triggered.connect(lambda: self.abrir_ver_inventario())
        ui.actionGenerar.triggered.connect(lambda: self.abrir_generar_reporte())
        ui.actionFactura_x_Cliente.triggered.connect(lambda: self.abrir_factura_x_cliente())
        ui.actionAgregarProv.triggered.connect(lambda: self.abrir_agregar_prov())
        ui.actionEliminarProv.triggered.connect(lambda: self.abrir_eliminar_prov())
        ui.actionBuscarProv.triggered.connect(lambda: self.abrir_buscar_prov())
        ui.actionModificarProv.triggered.connect(lambda: self.abrir_mod_prov())
        sys.exit(app.exec_())

    # * Funciones para abrir las ventanas
    def abrir_factura(self):
        self.ventana_factura = QtWidgets.QMainWindow()
        self.ui = Ui_RealizarFacturaWindow()
        self.ui.setupUi(self.ventana_factura)
        self.ventana_factura.show()

    def abrir_agregar_producto(self):
        self.ventana_inventario = QtWidgets.QMainWindow()
        self.ui = Ui_AddProductWindow()
        self.ui.setupUi(self.ventana_inventario)
        self.ventana_inventario.show()

    def abrir_busqueda_produto(self):
        self.ventana_busqueda_producto = QtWidgets.QMainWindow()
        ui = Ui_BusquedaProductoWindow()
        ui.setupUi(self.ventana_busqueda_producto)
        self.ventana_busqueda_producto.show()

    def abrir_eliminar_producto(self):
        self.ventana_eliminar_producto = QtWidgets.QMainWindow()
        self.ui = Ui_EliminarProductoWindow()
        self.ui.setupUi(self.ventana_eliminar_producto)
        self.ventana_eliminar_producto.show()

    def abrir_modificar_producto(self):
        self.ventana_modificar_producto = QtWidgets.QMainWindow()
        self.ui = Ui_ModificarProductoWindow()
        self.ui.setupUi(self.ventana_modificar_producto)
        self.ventana_modificar_producto.show()

    def abrir_ver_inventario(self):
        self.ventana_ver_inventario = QtWidgets.QMainWindow()
        self.ui = Ui_VerInventarioWindow()
        self.ui.setupUi(self.ventana_ver_inventario)
        self.ventana_ver_inventario.show()
    
    def abrir_generar_reporte(self):
        self.ventana_generar_reporte = QtWidgets.QMainWindow()
        self.ui = Ui_GenerarReporteWindow()
        self.ui.setupUi(self.ventana_generar_reporte)
        self.ventana_generar_reporte.show()
    
    def abrir_factura_x_cliente(self):
        self.ventana_factura_x_cliente = QtWidgets.QMainWindow()
        self.ui = Ui_FacturaClienteWindow()
        self.ui.setupUi(self.ventana_factura_x_cliente)
        self.ventana_factura_x_cliente.show()
    
    def abrir_agregar_prov(self):
        self.ventana_agregar_prov = QtWidgets.QMainWindow()
        self.ui = Ui_AgregarProvWindow()
        self.ui.setupUi(self.ventana_agregar_prov)
        self.ventana_agregar_prov.show()

    def abrir_mod_prov(self):
        self.ventana_mod_prov = QtWidgets.QMainWindow()
        self.ui = Ui_ModificarProvWindow()
        self.ui.setupUi(self.ventana_mod_prov)
        self.ventana_mod_prov.show()
    
    def abrir_eliminar_prov(self):
        self.ventana_eliminar_prov = QtWidgets.QMainWindow()
        self.ui = Ui_EliminarProvWindow()
        self.ui.setupUi(self.ventana_eliminar_prov)
        self.ventana_eliminar_prov.show()

    def abrir_buscar_prov(self):
        self.ventana_buscar_prov = QtWidgets.QMainWindow()
        self.ui = Ui_BuscarProvWindow()
        self.ui.setupUi(self.ventana_buscar_prov)
        self.ventana_buscar_prov.show()
    # ? ---------------------------------------


if __name__ == "__main__":
    main_window = Ui_MainWindow()
    main_window.open_PrincipalWindow()